version: "3.9"

services:
  djangoflix:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
     - ./djangoflix:/djangoflix
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=djangoflixdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
    

  db:
    image: postgres:13-alpine
    volumes:
     - djangoflix-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoflixdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes: 
  djangoflix-db-data:
