version: "3.9"

services:
  djangoflix:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
     - ./djangoflix:/djangoflix
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"