[tool.black]
line-length = 79  
quote = "'"
target-version = ['py36', 'py37', 'py38', 'py39'] 
exclude = ''' 
  /(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''