# Generated by Django 4.0.10 on 2023-09-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVShowProxy",
            fields=[],
            options={
                "verbose_name": "TV Show",
                "verbose_name_plural": "TV Shows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.playlist",),
        ),
        migrations.CreateModel(
            name="TVShowSeasonProxy",
            fields=[],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.playlist",),
        ),
        migrations.AddField(
            model_name="playlist",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.playlist",
            ),
        ),
    ]
