# Generated by Django 4.0.10 on 2023-09-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_tvshowproxy_tvshowseasonproxy_playlist_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieProxy",
            fields=[],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.playlist",),
        ),
        migrations.AddField(
            model_name="playlist",
            name="type",
            field=models.CharField(
                choices=[
                    ("MOV", "Movie"),
                    ("TVS", "TV Show"),
                    ("SEA", "Season"),
                    ("PLY", "Playlist"),
                ],
                default="PLY",
                max_length=3,
            ),
        ),
    ]
