# Generated by Django 4.0.10 on 2023-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_timestamp_video_updated_alter_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=210, unique=True),
        ),
    ]
